name: Node CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    # hashFiles has two bugs atm:
    # - can't do individual files
    # - / doesn't work on windows
    # https://github.com/actions/cache/issues/39
    # Unclear if we can just use the same cached yarn/maven artifacts on both though.
    - name: Cache node_modules on unix
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: node_modules
        key: unix-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          unix-node_modules-
    - name: Cache maven on unix
      uses: actions/cache@v1
      if: matrix.os != 'windows-latest'
      with:
        path: ~/.m2
        key: unix-m2-${{ hashFiles('**/shadow-cljs.edn') }}
        restore-keys: |
          unix-m2-
    - name: Cache node_modules on windows
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: node_modules
        key: windows-node_modules-${{ hashFiles('**\yarn.lock') }}
        restore-keys: |
          windows-node_modules-
    - name: Cache maven on windows
      uses: actions/cache@v1
      if: matrix.os == 'windows-latest'
      with:
        path: ~/.m2
        key: windows-m2-${{ hashFiles('**\shadow-cljs.edn') }}
        restore-keys: |
          windows-m2-
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Start background server
      run: yarn shadow-cljs start
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test:once
    - name: E2E
      run: yarn e2e
    - name: Archive Production Artifact
      # Only upload the Linux build.
      if: matrix.os == 'ubuntu-latest'    
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

  release:
    if: github.ref == 'refs/heads/master' && github.repository == 'filipesilva/create-cljs-app'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: dist  
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    # Test the release if one was made.
    # Would be nice to group these steps on the `if` conditional, but no way to do it yet.
    - name: Use Node.js 12.x
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Try to use release
      if: steps.semantic.outputs.new_release_published == 'true'
      run: yarn create cljs-app my-cljs-app
